/* User */
export const INIT_USER_STATE = 'INIT_USER_STATE'
export const RESET_USERINFO = 'RESET_USERINFO'
export const SET_USER_NEED_LOAD = 'SET_USER_NEED_LOAD'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const SIGNUP = 'SIGNUP'

export const SET_LOGIN = 'SET_LOGIN'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_USERID = 'SET_USERID'

export const ADD_ADMIN_CLUB = 'ADD_ADMIN_CLUB'
export const ADD_MEMBER_CLUB = 'ADD_MEMBER_CLUB'

export const VERIFY_TOKEN = 'VERIFY_TOKEN'

/* Club */
export const POST_CLUB = 'POST_CLUB'
export const GET_CLUBS = 'GET_CLUBS'
export const SET_CLUBS = 'SET_CLUBS'

export const INIT_CLUB_STATE = 'INIT_CLUB_STATE'

export const SET_CLUB_NAME = 'SET_CLUB_NAME'
export const SET_CLUB_ID = 'SET_CLUB_ID'
export const SET_CLUB_ADMIN = 'SET_CLUB_ADMIN'
export const SET_CLUB_SCOPE = 'SET_CLUB_SCOPE'
export const SET_CLUB_CATEGORY = 'SET_CLUB_CATEGORY'
export const SET_CLUB_INTRODUCTION = 'SET_CLUB_INTRODUCTION'
export const SET_FUTURE_EVENT = 'SET_FUTURE_EVENT'
export const SET_PAST_EVENT = 'SET_PAST_EVENT'

export const ADD_CLUB_BOARD = 'ADD_CLUB_BOARD'
export const ADD_CLUB_MEMBER = 'ADD_CLUB_MEMBER'
export const ADD_CLUB_WAITING = 'ADD_CLUB_WAITING'
export const ADD_CLUB_ADMIN = 'ADD_CLUB_ADMIN'
//export const ADD_FUTURE_EVENT = 'ADD_FUTURE_EVENT'
//export const ADD_PAST_EVENT = 'ADD_PAST_EVENT'

export const DELETE_CLUB_BOARD = 'DELETE_CLUB_BOARD'

/* Board */
export const GET_BOARD = 'GET_BOARD'
export const POST_BOARD = 'POST_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'

export const INIT_BOARD_STATE = 'INIT_BOARD_STATE'
export const RESET_BOARD_INFO = 'RESET_BOARD_INFO'
export const SET_BOARD_NEED_LOAD = 'SET_BOARD_NEED_LOAD'

export const SET_BOARD_NAME = 'SET_BOARD_NAME'
export const SET_BOARD_ID = 'SET_BOARD_ID'
export const ADD_BOARD_ARTICLE = 'ADD_BOARD_ARTICLE'
export const DELETE_BOARD_ARTICLE = 'DELETE_BOARD_ARTICLE'

export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS'
export const KICK_USER = 'KICK_USER'
export const GET_CLUB_USER_LIST = 'GET_CLUB_USER_LIST'
export const SET_CLUB_USER_LIST = 'SET_CLUB_USER_LIST'

/* Article */
export const GET_ARTICLE = 'GET_ARTICLE'
export const POST_ARTICLE = 'POST_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const PUT_ARTICLE = 'PUT_ARTICLE'

export const INIT_ARTICLE_STATE = 'INIT_ARTICLE_STATE'
export const RESET_ARTICLE_IS_EDIT = 'RESET_ARTICLE_IS_EDIT'
export const SET_ARTICLE_IS_EDIT = 'SET_ARTICLE_IS_EDIT'

export const SET_ARTICLE_TITLE = 'SET_ARTICLE_TITLE'
export const SET_ARTICLE_ID = 'SET_ARTICLE_ID'
export const SET_ARTICLE_CREATED_AT = 'SET_ARTICLE_CREATED_AT'
export const SET_ARTICLE_UPDATED_AT = 'SET_ARTICLE_UPDATED_AT'
export const SET_ARTICLE_CONTENT = 'SET_ARTICLE_CONTENT'
export const SET_ARTICLE_WRITER = 'SET_ARTICLE_WRITER'
export const SET_ARTICLE_BOARD = 'SET_ARTICLE_BOARD'
export const SET_ARTICLE_COMMENT = 'SET_ARTICLE_COMMENT'

export const POST_COMMENT = 'POST_COMMENT'
export const PUT_COMMENT = 'PUT_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

/* Search */
export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT'
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'

/* Event */
export const GET_EVENTS = 'GET_EVENTS'
export const POST_EVENT = 'POST_EVENT'
export const INIT_EVENT_STATE = 'INIT_EVENT_STATE'
export const SET_EVENT = 'SET_EVENT'
export const ADD_FUTURE_ATTENDEE = 'ADD_FUTURE_ATTENDEE'
export const ADD_FUTURE_ABSENTEE = 'ADD_FUTURE_ABSENTEE'
export const SET_PAST_ATTENDEES = 'SET_PAST_ATTENDEES'
export const PUT_FUTURE_ATTENDEE = 'PUT_FUTURE_ATTENDEE'
export const PUT_FUTURE_ABSENTEE = 'PUT_FUTURE_ABSENTEE'
export const POST_PAST_ATTENDEES = 'POST_PAST_ATTENDEES'
