/* User */
export const INIT_USER_STATE = 'INIT_USER_STATE'
export const RESET_USERINFO = 'RESET_USERINFO'
export const SET_USER_NEED_LOAD = 'SET_USER_NEED_LOAD'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const SIGNUP = 'SIGNUP'

export const SET_LOGIN = 'SET_LOGIN'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_USERID = 'SET_USERID'

export const ADD_ADMIN_CLUB = 'ADD_ADMIN_CLUB'
export const ADD_MEMBER_CLUB = 'ADD_MEMBER_CLUB'

export const VERIFY_TOKEN = 'VERIFY_TOKEN'

/* Club */
export const POST_CLUB = 'POST_CLUB'
export const GET_CLUBS = 'GET_CLUBS'
export const SET_CLUBS = 'SET_CLUBS'

export const INIT_CLUB_STATE = 'INIT_CLUB_STATE'
export const RESET_CLUBINFO = 'RESET_CLUBINFO'
export const SET_CLUB_NEED_LOAD = 'SET_CLUB_NEED_LOAD'

export const SET_CLUBNAME = 'SET_CLUBNAME'
export const SET_CLUBID = 'SET_CLUBID'
export const SET_CLUBADMIN = 'SET_CLUBADMIN'
export const SET_CLUBSCOPE = 'SET_CLUBSCOPE'
export const SET_CLUBCATEGORY = 'SET_CLUBCATEGORY'
export const SET_CLUBINTRODUCTION = 'SET_CLUBINTRODUCTION'

export const ADD_CLUBBOARD = 'ADD_CLUBBOARD'
export const ADD_CLUBMEMBER = 'ADD_CLUBMEMBER'
export const ADD_CLUBWAITING = 'ADD_CLUBWAITING'

export const DELETE_CLUBBOARD = 'DELETE_CLUBBOARD'

/* Board */
export const GET_BOARD = 'GET_BOARD'
export const POST_BOARD = 'POST_BOARD'
export const DELETE_BOARD = 'DELETE_BOARD'

export const INIT_BOARD_STATE = 'INIT_BOARD_STATE'
export const RESET_BOARDINFO = 'RESET_BOARDINFO'
export const SET_BOARD_NEED_LOAD = 'SET_BOARD_NEED_LOAD'

export const SET_BOARDNAME = 'SET_BOARDNAME'
export const SET_BOARDID = 'SET_BOARDID'
export const ADD_BOARDARTICLE = 'ADD_BOARDARTICLE'
export const DELETE_BOARDARTICLE = 'DELETE_BOARDARTICLE'

export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS'
export const KICK_USER = 'KICK_USER'
export const GET_CLUB_USER_LIST = 'GET_CLUB_USER_LIST'
export const SET_CLUB_USER_LIST = 'SET_CLUB_USER_LIST'

/* Article */
export const GET_ARTICLE = 'GET_ARTICLE'
export const POST_ARTICLE = 'POST_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const PUT_ARTICLE = 'PUT_ARTICLE'

export const INIT_ARTICLE_STATE = 'INIT_ARTICLE_STATE'
export const RESET_ARTICLE_ISEDIT = 'RESET_ARTICLE_EDIT'
export const SET_ARTICLE_ISEDIT = 'SET_ARTICLE_ISEDIT'

export const SET_ARTICLETITLE = 'SET_ARTICLETITLE'
export const SET_ARTICLEID = 'SET_ARTICLEID'
export const SET_ARTICLECREATEDAT = 'SET_ARTICLECREATEDAT'
export const SET_ARTICLEUPDATEDAT = 'SET_ARTICLEUPDATEDAT'
export const SET_ARTICLECONTENT = 'SET_ARTICLECONTENT'
export const SET_ARTICLEWRITER = 'SET_ARTICLEWRITER'
export const SET_ARTICLEBOARD = 'SET_ARTICLEBOARD'












