/* User */
export const INIT_USER_STATE = 'INIT_USER_STATE'
export const RESET_USERINFO = 'RESET_USERINFO'
export const SET_USER_NEED_LOAD = 'SET_USER_NEED_LOAD'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const SIGNUP = 'SIGNUP'

export const SET_LOGIN = 'SET_LOGIN'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_USERID = 'SET_USERID'

export const ADD_ADMIN_CLUB = 'ADD_ADMIN_CLUB'
export const ADD_MEMBER_CLUB = 'ADD_MEMBER_CLUB'

export const VERIFY_TOKEN = 'VERIFY_TOKEN'

/* Club */
export const POST_CLUB = 'POST_CLUB'
export const GET_CLUBS = 'GET_CLUBS'
export const SET_CLUBS = 'SET_CLUBS'
export const ADD_CLUBADMIN = 'ADD_CLUBADMIN'
export const ADD_CLUBMEMBER = 'ADD_CLUBMEMBER'
export const ADD_CLUBWAITING = 'ADD_CLUBWAITING'
export const ADD_CLUBBOARD = 'ADD_CLUBBOARD'
export const ADD_FUTURE_EVENT = 'ADD_FUTURE_EVENT'
export const ADD_PAST_EVENT = 'ADD_PAST_EVENT'
export const INIT_CLUB_STATE = 'INIT_CLUB_STATE'
export const RESET_CLUBINFO = 'RESET_CLUBINFO'
export const SET_CLUB_NEED_LOAD = 'SET_CLUB_NEED_LOAD'
export const SET_CLUBNAME = 'SET_CLUBNAME'
export const SET_CLUBID = 'SET_CLUBID'
export const SET_CLUBSCOPE = 'SET_CLUBSCOPE'
export const SET_CLUBCATEGORY = 'SET_CLUBCATEGORY'
export const SET_CLUBINTRODUCTION = 'SET_CLUBINTRODUCTION'

/* Event */
export const SET_EVENT_NEED_LOAD = 'SET_EVENT_NEED_LOAD'
export const GET_EVENTS = 'GET_EVENTS'
export const POST_EVENT = 'POST_EVENT'
export const INIT_EVENT_STATE = 'INIT_EVENT_STATE'
export const SET_EVENT = 'SET_EVENT'
export const ADD_FUTURE_ATTENDEE = 'ADD_FUTURE_ATTENDEE'
export const ADD_FUTURE_ABSENTEE = 'ADD_FUTURE_ABSENTEE'
export const ADD_PAST_ATTENDEE = 'ADD_PAST_ATTENDEE'

export const PUT_FUTURE_ATTENDEE = 'PUT_FUTURE_ATTENDEE'